export const fashionData = [
  {
    id: 1,
    fashion_genre: "Design Objects",
    name: "American Design Club",
    image: "",
    link: "",
  },
  {
    id: 2,
    fashion_genre: "Jewelry",
    name: "Beeshaus & Raum NYC",
    image: "",
    link: "",
  },
  {
    id: 3,
    fashion_genre: "Jewelry",
    name: "Beroep Tech",
    image: "",
    link: "",
  },
  {
    id: 4,
    fashion_genre: "Bonsai Shop",
    name: "Dandy Farmer Bonsai Shop",
    image: "",
    link: "",
  },
  {
    id: 5,
    fashion_genre: "Fashion Apparel",
    name: "Friend Of A Friend Studio",
    image: "",
    link: "",
  },
  {
    id: 6,
    fashion_genre: "Design Objects",
    name: "Leibal",
    image: "",
    link: "",
  },
  {
    id: 7,
    fashion_genre: "K Pop Apparel and Merchandise",
    name: "Mandu Apparel",
    image: "",
    link: "",
  },
  {
    id: 8,
    fashion_genre: "Home Goods",
    name: "Mogutable",
    image: "",
    link: "",
  },
  {
    id: 9,
    fashion_genre: "Jewelry",
    name: "Mottive",
    image: "",
    link: "",
  },
  {
    id: 10,
    fashion_genre: "Newstand and Magazines",
    name: "Office Magazine Newstand",
    image: "",
    link: "",
  },
  {
    id: 11,
    fashion_genre: "Fashion Apparel",
    name: "Preppy Trendy",
    image: "",
    link: "",
  },
  {
    id: 12,
    fashion_genre: "Sunglasses",
    name: "Savage Anchor",
    image: "",
    link: "",
  },
  {
    id: 13,
    fashion_genre: "Jewelry",
    name: "Seven 50",
    image: "",
    link: "",
  },
  {
    id: 14,
    fashion_genre: "Sustainable lifestyle store",
    name: "Siizu",
    image: "",
    link: "",
  },
  {
    id: 15,
    fashion_genre: "Jewelry",
    name: "Swagychic",
    image: "",
    link: "",
  },
];
